server:
  port: 80

beetl:
  resource-auto-check: true       #热加载beetl模板

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
